# Site
title: tanto259.name
description: Student, Gamer, Developer, Cybersecurity Enthusiast
url: https://tanto259.name
logo: halve.png                                       
locale: en_US
maintenance: false

# Left Block Images
background:
  homepage: assets/images/home.jpg                           
  post-list: assets/images/postlist.jpg             
  default-post: assets/images/post.jpg  

# Jekyll
permalink:          /:title
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         _sass
  style:            compressed

# Meta Tags
google-verify: 47gabr9UPrQqoFY1CCpP13pYagL4RKBU8xImeq_s5EQ
bing-verify: 0C8DA626DE53E04C6AF918B5FB85176E
pinterest-verify: 59d7967f758b1f035e23d436b2778b57
wot-verify: 24f37ed1b7a537b44f55
norton-safeweb: 9u2bacgc2l2jiz2sknjz4aw48ft2kk3edmomxcmozsx2nzxugydtz58uutsxm3f9qrfccybu4umvgp8lj7nng-8e4m3bhde6ezjnp8lxn971tjumc00ncl-bdti1gm28

# Social Links
email:              https://tanto259.name/contact
#google.plus:       username
twitter:            tanto259
facebook:           tanto259
github:             tanto259
stackoverflow:      6789877/tanto259
stackexchange:      8492733/tanto259
quora:              Hartanto-Ario-Widjaya
#linkedin:          username
#xing:              username
instagram:          tanto259
#lastfm:            username
#tumblr:            username
pinterest:          tanto259
#foursquare:        username
steam:              tanto259
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
keybase:            tanto259
#xmpp:              username
reddit:             tanto259
hackernews:         tanto259
#behance:           username

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages, _redirects, _headers]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store, licensing]
